### ISSUE TITLE
GL Detail API

### ISSUE THREAD

**Issue by CPAanalytics** [fylein/sageintacct-sdk-py#23]
Hey guys I'm using your SDK to move data between powerbi and Intacct and noticed that you are missing a class to pull from the GL detail.  Let me know if you would like me to contribute the class I wrote.

**Comment by ashwin1111** [comment]
Hey there @CPAanalytics, we are open to accept contributions, please go ahead and create a pull request on the missing class. Thanks.

**Comment by CPAanalytics** [comment]
GL Detail class added.
