### ISSUE TITLE
How to work with the Sandbox Account?

### ISSUE THREAD

**Issue by lowercase00** [fylein/sageintacct-sdk-py#29]
Hi, thanks for sharing the code.
I couldn't find the variables to pass the Sandbox Credentials?
I wonder if the password-less logic would require a change in the SDK logic, or is just a small adjustment to allow these fields, or perhaps use one of the existing parameters in the initializer. 

[Development Docs](https://developer.sage.com/api/payments/test-in-sandbox.html)
```
vendorName: sandbox
integrationKey: hJYxsw7HLbj40cB8udES8CDRFLhuJ8G54O6rDpUXvE6hYDrria
integrationPassword: o2iHSrFybYMZpmWOQMuhsXP52V4fBtpuSDshrKDSWsBY1OiN6hwd9Kb12z4j5Us5u
```

Thanks!

**Comment by ashwin1111** [comment]
@lowercase00 
This SDK is intended to support [Sage Intacct APIs](https://developer.intacct.com/api/) and not [Sage](https://developer.sage.com/api/payments/test-in-sandbox.html)

Thanks
