### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by emoncse** [fylein/sageintacct-sdk-py#58]
I can not update customer data using the update method. If it is possible to make good documentation for this SDK on updating custom fields using CUSTOMERID, it will be beneficial for users.

**Comment by ashwin1111** [comment]
Sorry, we don't have documentation for updating the custom field. You can take a look at [https://developer.intacct.com/api/](https://developer.intacct.com/api/) based on the module that you're looking to update and send a required payload to the update() method. Let me know if you're facing any issues.
