### ISSUE TITLE
Looking for approach to the creation of Funds Transfer and Bank Fee Entries

### ISSUE THREAD

**Issue by JamesSThompson-FDH** [fylein/sageintacct-sdk-py#87]
Is there an approach for creating entries for Funds Transfers and Bank Fee Entries? I only see the query options in the API, is there a post method that can be used to create these entries?

**Comment by ashwin1111** [comment]
Hi @JamesSThompson-FDH, you can create relevant classes for the missing APIs - we're open to contributions. We don't have support for the couple of APIs you've mentioned above.
