### ISSUE TITLE
Fix GL Detail and Journal Entries API Access

### ISSUE THREAD

**Issue by mattrobinson412** [fylein/sageintacct-sdk-py#93]
## The Problem
- When querying the endpoints 'gl_detail' or 'journal_entries', this error appears, even on `connection.gl_detail.get_all()`:
`WARNING:root:{'response': {'control': {'status': 'success', 'senderid': 'Entrusted', 'controlid': '2024-10-03 21:38:09.552366', 'uniqueid': 'false', 'dtdversion': '3.0'}, 'operation': {'authentication': {'status': 'success', 'userid': 'SupabaseAPI', 'companyid': 'Entrusted', 'locationid': None, 'sessiontimestamp': '2024-10-04T01:38:10+00:00', 'sessiontimeout': '2024-10-04T07:38:10+00:00'}, 'result': {'status': 'failure', 'function': 'query', 'controlid': '3a457daa-4fc1-44fc-a8af-f4db998309ba', 'errormessage': {'error': {'errorno': 'XL03000010', 'description': None, 'description2': 'Field requested is not valid: gldetail.STATUS [Support ID: VuCAMWEB033%7EZv9HAP1k0PG7xhd-Cqn9zQAAABg]', 'correction': None}}}}}}`

Specifically, the value in **description2** is noteworthy:
`'description2': 'Field requested is not valid: gldetail.STATUS [Support ID: VuCAMWEB033%7EZv9HAP1k0PG7xhd-Cqn9zQAAABg]'`

This appears to be related to the _api_base.py_ file, and specifcally the _count_ method around lines 357-369:
`def count(self):
        get_count = {
            'query': {
                'object': self.__dimension,
                'select': {
                    'field': 'RECORDNO'
                },
                'filter': {
                    'equalto': {'field': 'STATUS', 'value': 'active'}
                },
                'pagesize': '1'
            }
        }`

Would anyone be able to remedy this? I'm happy to submit a pull request if that would help as well. Thanks!

**Comment by ashwin1111** [comment]
@mattrobinson412 we did few recent changes around the way count is retrieved and had a bug in the area, I've patched it in version [1.23.1](https://github.com/fylein/sageintacct-sdk-py/releases/tag/1.23.1). Please use latest version and let us know if you still face the issue
